#!/bin/bash

echo 'Установка тем'
aurman -S osx-arc-shadow xcursor-breeze-serie-obsidian papirus-maia-icon-theme-git --noconfirm

echo 'Создаем нужные директории'
sudo pacman -S xdg-user-dirs
xdg-user-dirs-update
mkdir ~/Dropbox/
mkdir ~/Dropbox/WALLPAPERS
mkdir ~/Dropbox/WALLPAPERS/GREEN/

echo 'Качаем и устанавливаем настройки Xfce'
# Чтобы сделать копию ваших настоек XFCE выполните команду ниже.
# tar -czf xfce4.tar.gz ~/.config/xfce4
# Выгрузите архив в интернет и скорректируйте ссылку на XFCE файл заменив ссылку http://ordanax.ru/arch_linux/xfce4.tar.gz на свою.
cd ~/Downloads
wget http://ordanax.ru/arch/xfce4.tar.gz
#rm -rf ~/.config/xfce4
tar -xzf xfce4.tar.gz -C /

echo 'Ставим лого ArchLinux в меню'
wget ordanax.ru/arch/archlinux_logo.png
sudo mv -f ~/Downloads/archlinux_logo.png /usr/share/pixmaps/archlinux_logo.png

echo 'Ставим обои на рабочий стол'
wget ordanax.ru/arch/Deepin_Linux_Manjaro.jpg
sudo mv -f ~/Downloads/Deepin_Linux_Manjaro.jpg ~/Dropbox/WALLPAPERS/GREEN/Deepin_Linux_Manjaro.jpg
rm -rf ~/Downloads/*

echo 'Установка завершена!'
rm -rf ~/arch_3.sh
