#
title: Ctlos Linux WIKI
display_title: CTLOS LINUX WIKI
url: https://ctlos.github.io
baseurl: /wiki
github_repo_url: https://github.com/ctlos/wiki
google_analytics: UA-90439782-2
ya_metrika: 47541358
google_verification: 6GXUozcEfaPdh8Qcr-0qBY2AV8MkL-QoQ66FpbytieM
show_full_navigation: true
disqus_shortname: ctlos

# jekyll-seo-tag
logo: /assets/img/siteicon.png
description: Wiki Ctlos Linux.
social:
  name: Ctlos
  links:
    - https://twitter.com/ctloslin
    - https://github.com/ctlos
twitter:
  username: ctloslin

# permalink: pretty
permalink: /:title/

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-archives
  - jekyll-paginate
  - jekyll-mentions
  - jekyll-redirect-from
  - jemoji

include: ["_pages"]

exclude:

sass:
  style: compressed
  sass_dir: _sass

collections:
  docs:
    title: Ctlos Linux Wiki
    permalink: /:path/
    output: true

defaults:
  -
    scope:
      path: ""
    values:
      image: /assets/img/siteicon.png
      layout: default
  -
    scope:
      path: ""
      type: "docs"
    values:
      layout: default
      seo:
        type: Article
      _comments:
        category: Group navigation links with this field
        order: Used to sort links in the navigation
      _options:
        content:
          width: 800
          height: 2000
  -
    scope:
      path: ""
      type: "posts"
    values:
      _comments:
        type: Marks the impact of this release

types:
  - major
  - minor
  - patch