#!/bin/bash
#Author Alex Boyko 
echo 'Скрипт сделан на основе чеклиста Бойко Алексея по Установке ArchLinux'
read -p "Пауза 3 ceк." -t 3
echo 'Ссылка на чек лист есть в группе vk.com/arch4u'
read -p "Пауза 3 ceк." -t 3
echo '2.1 Установка раскладки клавиатуры'
read -p "Пауза 3 ceк." -t 3
loadkeys ru
setfont cyr-sun16
echo '2.4 Создание разделов BTRFS и монтирование дисков'
read -p "Пауза 3 ceк." -t 3
mkfs.btrfs -f /dev/sda1
mount /dev/sda1 /mnt
btrfs subvolume create /mnt/sv_root
btrfs subvolume create /mnt/sv_home
btrfs subvolume create /mnt/sv_snapshots
umount /mnt
mount -o subvol=sv_root,compress=lzo,autodefrag /dev/sda1 /mnt
mkdir /mnt/home
mount -o subvol=sv_home,compress=lzo,autodefrag /dev/sda1 /mnt/home
mkdir /mnt/snapshots
mount -o subvol=sv_snapshots,compress=lzo,autodefrag /dev/sda1 /mnt/snapshots
echo '3.1 Выбор зеркал для загрузки. Используем программу Reflector'
read -p "Пауза 3 ceк." -t 3
pacman -Sy --noconfirm --noprogressbar --quiet reflector
pacman -S --noconfirm --needed --noprogressbar --quiet reflector
reflector -l 3 --sort rate --save /etc/pacman.d/mirrorlist
echo '3.2 Установка основных пакетов'
read -p "Пауза 3 ceк." -t 3
pacstrap /mnt base base-devel
echo '3.3 Настройка системы'
read -p "Пауза 3 ceк." -t 3
genfstab -pU /mnt >> /mnt/etc/fstab
echo 'Переходим в установлнную систему'
read -p "Пауза 3 ceк." -t 3
arch-chroot /mnt
echo "ArchLinux" > /etc/hostname
ln -svf /usr/share/zoneinfo/Asia/Yekaterinburg /etc/localtime
echo '3.4 Добавляем русскую локаль системы'
read -p "Пауза 3 ceк." -t 3
echo -e "en_US.UTF-8 UTF-8\nru_RU.UTF-8 UTF-8" >> /etc/locale.gen
echo 'Обновим текущую локаль системы'
read -p "Пауза 3 ceк." -t 3
locale-gen
echo 'Указываем язык системы'
read -p "Пауза 3 ceк." -t 3
echo 'LANG="ru_RU.UTF-8"' > /etc/locale.conf
echo 'Вписываем KEYMAP=ru FONT=cyr-sun16'
read -p "Пауза 3 ceк." -t 3
echo 'KEYMAP=ru' >> /etc/vconsole.conf
echo 'FONT=cyr-sun16' >> /etc/vconsole.conf
echo 'Создадим загрузочный RAM диск'
read -p "Пауза 3 ceк." -t 3
mkinitcpio -p linux
echo 'Создаем root пароль'
read -p "Пауза 15 ceк." -t 15
passwd
echo '3.5 Устанавливаем загрузчик'
read -p "Пауза 3 ceк." -t 3
pacman -Syy
pacman -S grub --noconfirm --noprogressbar --quiet
grub-install /dev/sda
echo 'Обновляем grub.cfg'
read -p "Пауза 3 ceк." -t 3
grub-mkconfig -o /boot/grub/grub.cfg
read -p "Пауза 3 ceк." -t 3
echo 'Ставим программу для Wi-fi'
pacman -S dialog wpa_supplicant --noconfirm --noprogressbar --quiet
echo 'Добавляем пользователя'
useradd -m -g users -G wheel -s /bin/bash ordanax
echo 'Устанавливаем пароль пользователя'
read -p "Пауза 15 ceк." -t 15
passwd ordanax
echo 'Устанавливаем SUDO'
read -p "Пауза 3 ceк." -t 3
echo '%wheel ALL=(ALL) ALL' >> /etc/sudoers
echo 'Раскомментируем репозиторий multilib Для работы 32-битных приложений в 64-битной системе.'
read -p "Пауза 3 ceк." -t 3
echo '[multilib]' >> /etc/pacman.d/mirrorlist
echo 'Include = /etc/pacman.d/mirrorlist' >> /etc/pacman.d/mirrorlist
pacman -Syy
echo 'Ставим иксы и драйвера'
read -p "Пауза 3 ceк." -t 3
pacman -S xorg-server xorg-drivers
echo 'Ставим Xfce, LXDM и сеть'
read -p "Пауза 3 ceк." -t 3
pacman -S --noconfirm xfce4 xfce4-goodies lxdm networkmanager network-manager-applet ppp ttf-liberation ttf-dejavu
echo 'Подключаем автозагрузку менеджера входа и интернет'
read -p "Пауза 3 ceк." -t 3
systemctl enable lxdm NetworkManager
echo 'Установка AUR (aurman)'
sudo pacman -Syy
git clone https://github.com/polygamma/aurman.git
cd aurman
makepkg -si
cd ..
rm -rf aurman
echo 'Установка программ'
read -p "Пауза 3 ceк." -t 3
pacman -S firefox obs-studio veracrypt freemind filezilla cherrytree gimp libreoffice libreoffice-fresh-ru kdenlive audacity pidgin screenfetch vlc qt4 ufw qbittorrent f2fs-tools dosfstools ntfs-3g alsa-lib alsa-utils gnome-calculator file-roller p7zip unrar gvfs aspell-ru pulseaudio --noconfirm --noprogressbar --quiet
aurman -S dropbox joxi obs-linuxbrowser xflux xflux-gui-git purple-vk-plugin purple-facebook pidgin-encryption sublime-text2 hunspell-ru pamac-aur osx-arc-shadow breeze-obsidian-cursor-theme papirus-maia-icon-theme-git --noconfirm --noprogressbar --quiet
echo 'Включаем сетевой экран'
read -p "Пауза 3 ceк." -t 3
ufw enable
echo 'Установка завершена! Перезагружаемся. И настраиваем с пункта 5.6 Настройки Xfce'
read -p "Пауза 15 ceк." -t 15
exit
umount -R /mnt
reboot
